[package]
name = "aws-lambda-runtime-codec"
version = "0.1.0"
authors = ["Kit Ewbank <Christopher.Ewbank@capitalone.com>"]
edition = "2018"

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"
