[package]
name = "provider"
version = "0.7.0"
authors = ["Kit Ewbank <Kit_Ewbank@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
log = "0.4.8"
anyhow = "1.0.28"
wascc-codec = "0.6.0"
reqwest = { version = "0.10.4", features = ["blocking", "json"] }
serde = "1.0.106"
serde_json = "1.0.51"
codec = { path = "../codec" }
aws_lambda_events = { git = "https://github.com/ewbankkit/aws-lambda-events", branch = "include-aws-lambda-go.pr-280" }
base64 = "0.12.0"
url = "2.1.1"
thiserror = "1.0.15"

[dev-dependencies]
httptest = "0.13.1"
