[package]
name = "aws-lambda-runtime-provider"
version = "0.1.0"
authors = ["Kit Ewbank <Kit_Ewbank@hotmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
wascc-codec = "0.5.0"
reqwest = { version = "0.10.3", features = ["blocking", "json"] }
serde = "1.0.104"
serde_json = "1.0.48"
aws-lambda-runtime-codec = { path = "../codec", version = "^0.1" }
