[package]
name = "provider"
version = "0.1.1"
authors = ["Kit Ewbank <Kit_Ewbank@hotmail.com>"]
edition = "2018"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
anyhow = "1.0.28"
wascc-codec = "0.5.2"
reqwest = { version = "0.10.4", features = ["blocking", "json"] }
serde = "1.0.105"
serde_json = "1.0.50"
codec = { path = "../codec" }
aws_lambda_events = "0.2.7"
